### PR TITLE
Switch to dts-css-modules-loader to generate types

### PR DESCRIPTION
**Pull request by nwehner**
I was able to get Gatsby to generate types and correctly insert the styles by switching over to the `dts-css-modules-loader` module. I also updated the dependencies and added a few more peer dependencies. I haven't gotten the included tests to pass, however.

### CODE REVIEW

**Comment by nwehner** [comment]
The latest commit (3e08164) brings back the MiniCssExtractPlugin to fix the undefined locals bug. It also uses Gatsby's configured `style-loader` and `css-loader` so that server side rendering can occur.

**Comment by nwehner** [comment]
While Webpack doesn't throw any errors, only some styles are applied if doing a production build (development build seems to work fine...). TypeScript says that "styles.module.scss.d.ts is not a module" wherever I import styles. Ugh....

**Comment by nwehner** [comment]
99% of the way there! Everything finally builds correctly in both development and production environments, and types are generated as expected. However, if I try to import a style, say `import { myStyle } from '../style/styles.module.scss';` then TypeScript shows an error that "File '.../style/styles.module.scss.d.ts' is not a module." which doesn't make sense, given the import isn't even for the .d.ts file

**Comment by nwehner** [comment]
FINALLY! Everything seems to be working 100% for me on Development and Production builds this time around. Please test like whoa :)

**Comment by Debens** [comment]
Thank you for putting this together 🙏 It's very much appreciated, I'll try and take a look at this as soon as I get a sec

**Review by Debens — APPROVED** [review]
Thank you for your contribution

**Pull request merged**
